### ISSUE TITLE
Lifecycle does not trigger on_eos/on_body_chunk callbacks

### ISSUE THREAD

**Issue by blind-oracle** [Ptrskay3/axum-prometheus#32] opened 2023-09-14 12:27 UTC
Hello! Thanks for the nice library. I have a question/problem not about axum_prometheus itself, but about Lifecycle module.

I've set it up to act on when the body is fully streamed and I can't get the callbacks. The `prepare`/`on_response` works fine, but `on_eos`/`on_body_chunk` does not get fired for some reason. `on_failure` is also silent when that happens.

Would be grateful for any hints, do I need something special for them to work?

**Comment by Ptrskay3** [comment] 2023-09-14 13:53
Hi, thank you!

It's hard to say in general what might go wrong there. Do you have a minimal reproducible example for this?

The first thing that comes to my mind is:
Are you implementing [Callbacks](https://docs.rs/axum-prometheus/latest/axum_prometheus/lifecycle/trait.Callbacks.html) fully? The default implementation for `on_failure`, `on_eos` and `on_body_chunk` is empty, so they don't do anything if you don't specify them in your `impl Callback`.

**Comment by blind-oracle** [comment] 2023-09-14 14:25
Thanks for the answer!

> Do you have a minimal reproducible example for this?

I'll try to bake some test code.

> Are you implementing [Callbacks](https://docs.rs/axum-prometheus/latest/axum_prometheus/lifecycle/trait.Callbacks.html) fully? The default implementation for on_failure, on_eos and on_body_chunk is empty, so they don't do anything unless you specify them in your impl Callback.

Of course, I have `Traffic` struct (just named the same as in your library) that implements `Callback` and it has all 4 methods defined.

I'm doing `curl` against my service to fetch some rather big response and get only logs from `on_response` callback, though the request executes successfully.

`on_response` gets called and receives correct `Self::Data` from `prepare`, all is good here. But no later callbacks are ever executed, they currently now just have some `info!` to show that they're called. `on_response` also has an `info!` which is printed out fine.

**Comment by blind-oracle** [comment] 2023-09-14 16:37
Here's the simple PoC that I expected to work: https://github.com/blind-oracle/httptest/blob/main/main.rs

In the console I see only `response generated`, probably I'm missing something simple.

**Comment by Ptrskay3** [comment] 2023-09-14 16:57
From a quick look, I made some [interesting decisions](https://github.com/Ptrskay3/axum-prometheus/blob/master/src/lifecycle/body.rs#L33-L55) with `poll_data` (and arguably `poll_trailers` too), and `on_body_chunk` is not called if the response body is fully processed in one pass. Also, if the classification resulted in an error, `on_failure` is not called either.

This doesn't  very much seems wrong to me at the moment — I think I'll revisit this part when I find the time, probably at weekend (or if you're familiar with manual futures and the tower ecosystem, PRs are always welcome :smile:).

**Comment by Ptrskay3** [comment] 2023-09-17 07:22
What would be your use case @blind-oracle? There are some design decisions to be made: Do you expect `Callbacks::Data` to be present in all callbacks? If yes, it needs to be cloned across some handlers (most likely in `on_body_chunk`, since it's kind of expected be to always called), which we don't do currently.

**Comment by blind-oracle** [comment] 2023-09-17 08:09
@Ptrskay3 my initial use-case was to measure the response body size. Since there's no easy way to do it in Axum/Tower (that I know of) it would be nice to have a mutable `Data` in `on_body_chunk` where I can increment some counter with the chunk size and then have access to it in the `on_eos`.

Currently I kinda had done that using custom `Body` that implements `Http::Body`, but not sure if it's better. Also I have problems doing callbacks there since the trait uses `Pin`

**Comment by Ptrskay3** [comment] 2023-09-17 08:32
I see. To be honest, I'm a little hesitant to make this change, since this crate is really about Prometheus HTTP metrics, but on the other hand, response body size may be one of them, it just happens to be unsupported in most Prometheus middlewares that I know about. 

The new design should be on par with how [`TraceLayer` handles](https://docs.rs/tower-http/latest/tower_http/trace/index.html#when-the-callbacks-are-called) these events, and that inevitably means we need to introduce some overhead because of cloning — even though in axum prometheus `on_body_chunk`, `on_eos` and `on_failure` are not used.

Let me experiment with this for some time, and we'll see what works the best. It's possible that another crate is more appropriate.

**Comment by blind-oracle** [comment] 2023-09-17 08:36
Yes, in my case it's exactly Prometheus metrics where I need the response body size. Since it can be arbitrarily big in our case, we can't buffer it fully to easily examine, so I have to come up with some streaming solution. And yeah, I couldn't find any existing solution to measure it as a metric.

Thanks, maybe we can make this optional somehow (if not - then yes, probably another crate would be feasible...)

**Comment by blind-oracle** [comment] 2023-09-28 15:09
Sorry for late answer. Thanks!

Though in the mean time I already moved to my own implementation of a custom body that would count the number of bytes streamed. I had a lot of surprises there with how consumers use the `http::Body` trait and decide when the stream is finished:
* If `Poll(None)` is returned from `poll_data()`
* If `size_hint()` provides exact body size, does not wait for `Poll(None)`
* If there's a `Content-Length` header in the response then the consumer expects exactly this number of bytes, also does not wait for `Poll(None)`

In you case does `on_body_chunk` gets called regardless of these conditions?
In your iml

**Comment by blind-oracle** [comment] 2023-09-28 15:59
> I wonder how would it be possible to see whether size_hint provides exact size, or the Content-Length header.

This is easy to check if you have access to inner body, in case if `size_hint().exact()` is `Some()` then you have the exact size. In this case probably it's not worth peeking through all chunks and one can just use that number.

Not sure if that will always be the case if there's a `Content-Length` header since it's not a part of the body and caller *might* have access to headers too and just call `Poll()` until it gets the expected number.

One example of such bodies is `http_body::Full` which are single-chunk bodies - they have an exact size always. Axum creates these bodies when you have a known length `Response` e.g. from String etc.

**Comment by Ptrskay3** [comment] 2023-09-28 16:13
Thanks, I found out about `size_hint` in the meanwhile. The hard part is definitely the `Content-Length`, where the only option for us to rely on axum to set an appropriate `Body` implementation (and can we even detect it somehow?). I'll have to check and experiment. This callbacks API probably has to change too in order to take these new constraints into account. Thank you for the valuable info.

**Comment by Ptrskay3** [comment] 2023-10-02 07:27
@blind-oracle I think in #33 I mostly fixed this.  Added the  `PrometheusMetricLayerBuilder::enable_response_body_size` function to opt-in for response body size tracking. The internals are not really cleaned up yet, but otherwise the functionality should be working now. Could you check whether it fits your use case?

**Comment by Ptrskay3** [comment] 2023-11-24 08:37
I've just merged #33, I hope that suits your needs. I think I'm closing this then.

**Closed by Ptrskay3** 2023-11-24 08:37 UTC
Labels: bug, question
